### ISSUE TITLE
Investigate relay memory buildup

### ISSUE THREAD

**Issue by suhasHere** [Quicr/quicrq#105]
It has seen that cache memory increases over time when there is active session. Need to see if we are leaking memory

**Comment by huitema** [comment]
I think I understand what is happening. The code of `quicrq_app.c` includes:
```
    /* If relay or origin, delete cached entries longer than 2 minute */
    quicrq_set_cache_duration(cb_ctx.qr_ctx, 120000000);
```
That seems quite high. Two minutes of build up means something like 5,000 video frames, probably about 10MB. Multiply by many streams and many clients, that can mean quite a lot of memory. We want a shorter timer, but how much shorter?

**Comment by suhasHere** [comment]
@huitema  as chatted, 10s would do for this timer.

**Comment by huitema** [comment]
Timer was set to 10seconds in PR #112. Issue is reported fixed after trials of new version.
