### ISSUE TITLE
Do we need a license?

### ISSUE THREAD

**Issue by huitema** [Quicr/quicrq#128]
Looking at https://github.com/Quicr/transport/pull/2 by @fluffy . Do we need to add the same license to this depot?

**Comment by fluffy** [comment]
Yes, we do. Cisco would be fine with MIT or BSD 2 clause for whatever our part of this may be. Would one of those work for you ?

**Comment by huitema** [comment]
This is a repo in the GitHub "quicr" org, so I suppose it would be good to just use whatever you use for other open source projects in this org. Maybe copy https://github.com/Quicr/quicr/blob/main/LICENSE

**Comment by huitema** [comment]
See PR #129
