### ISSUE TITLE
Demo client usage

### ISSUE THREAD

**Issue by clarkzjw** [Quicr/quicrq#96]
I'm a little confused about how to use the demo program `quicrq_app`. 

Following the README, I first run `quicrq_app` in server mode,

```
./quicrq_app -q qlog -c ./ca/ca-cert.pem -k ./ca/server-key.pem -p 4433 -w ./tests server
```

The `tests` folder contains `video1_source.bin`.

And run `quicrq_app` in client mode,

```
./quicrq_app client localhost d 4433 get:video1_source.bin:./tmp
```

and the client only shows

```
QUICRQ Version 0.22, Picoquic Version 1.04a
Waiting for packets.
```

In this case, I try to connect the client directly to the server and no relay node was set up. Is this the right syntax for scenarios? I'm confused by `*{{'get'|'post'}':'<url>':'<path>[':'<log_path>]';'}`.

Update: I also tried to add a relay like this:
```
./quicrq_app -c ./ca/ca-cert.pem -k ./ca/server-key.pem -p 4434 -w ./tests relay localhost s 4433
```

and let the client to connect to the relay:
```
./quicrq_app client localhost s 4434 get:video1_source.bin:./tmp
```

**Comment by VidarHUN** [comment]
Hi,
I also have the same problem. I can run a server like this:
```shell
./quicrq_app -p 3000 -c certs/cert.pem -k certs/key.pem server
QUICRQ Version 0.30, Picoquic Version 1.1.8.1
Waiting for packets.
```
And the client:
```shell
./quicrq_app client 127.0.0.1 d 3000 get:tests/video1_source.bin:./tmp                         
QUICRQ Version 0.30, Picoquic Version 1.1.8.1
Waiting for packets.
```
What am I doing wrong?

**Comment by clarkzjw** [comment]
@VidarHUN You can check https://github.com/Quicr/quicrq/issues/104#issuecomment-1360082364

**Comment by VidarHUN** [comment]
Thanks for the quick response. I somehow missed that issue...
